# SPDX-FileCopyrightText: 2020-2022 Alex Grinman <me@alexgr.in>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
    "portalgun_lib",
    "portalgun",
    "portalgun_moon",
]

exclude = [
    "portalgun_proxy"
]

[profile.dev]
split-debuginfo = "unpacked"
