# SPDX-FileCopyrightText: 2020-2022 Alex Grinman <me@alexgr.in>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
    "tunnelto_lib",
    "tunnelto",
    "tunnelto_server",
]

exclude = [
    "tunnelto_proxy"
]

[profile.dev]
split-debuginfo = "unpacked"