name: Publish to crates.io
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - run: cd tunnelto_lib && cargo publish --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"
      - run: cd tunnelto && cargo publish --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"

